# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    exclude:
      - master
      - develop
pr:
  branches:
    include:
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Setup
  jobs:
  - job: Prueba
    steps:
    - script: sudo apt-get install jq -y; jq parameters.json
- stage: UnitTest
  jobs:
  - job: Lote1
    steps:
    - script: echo Lote 1!; sleep 20
  - job: Lote2
    steps:
    - script: echo Lote 2!; pwd; date; sleep 10
  - job: Lote3
    steps:
    - script: echo Lote 3!; sleep 15
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
