# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    exclude:
      - master
      - develop
pr:
  branches:
    include:
    - feature/*

variables:
- template: simple-param.yml
- name: label

stages:
- stage: Setup
  jobs:
  - job: SetAgent
    steps:
    - script: ${{ if eq(variables.appName, "PolicyCenter") }}; then; label='SlavePR'
- stage: UnitTest
  jobs:
  - job: Lote1
    steps:
    - script: echo $label; sleep 2; echovar="Prueba"
  - job: Lote2
    steps:
    - script: pwd; date; sleep 1
  - job: Lote3
    steps:
    - script: echo Lote 3!; sleep 1
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo $echovar
