# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    exclude:
      - master
      - develop
pr:
  branches:
    include:
    - feature/*

variables:
- template: simple-param.yml
- name: label

stages:
- stage: StaticAnalysis&Integrity
  pool:
    vmImage: ${{ variables.label }}
  jobs:
  - job: VerifyResources
    timeoutInMinutes: 40
    condition: and(succeeded(), ne(variables.appName, 'PolicyCenter'))
    steps: 
      - script: ant verify-resources -DmaxSPVInclusions=1000
  - job: StaticAnalysisUnitTest
    timeoutInMinutes: 40
    steps:
    - script: ant sura.gosu-codenarc-test -Dpath=ic -f ${{ variables.appName }}/modules/ant/build.xml
    - task: PublishTestResults@2
      inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'build/reports/codenarc/html/*.html'
  - job: JavaAPI
    timeoutInMinutes: 40
    steps:
    - script: ant regen-java-api -Dpath=ic -f ${{ variables.appName }}/modules/ant/build.xml
  - job: CodeAnalysis
    timeoutInMinutes: 40
    steps:
    - script: ant code-analysis -Dpath=ic -f ${{ variables.appName }}/modules/ant/build.xml
    - task: PublishTestResults@2
      inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'build/reports/codenarc/html/*.html'
  - job: SoapAPI
    timeoutInMinutes: 40
    steps:
    - script: ant regen-soap-api -Dpath=ic -f ${{ variables.appName }}/modules/ant/build.xml
  - job: StaticNamesAnalysis
    timeoutInMinutes: 40
    steps:
    - script: ant sura.gosu-codenarc -Dpath=ic -f ${{ variables.appName }}/modules/ant/build.xml
    - task: PublishTestResults@2
      inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'build/reports/codenarc/html/*.html'


- stage: UnitTest
  jobs:
  - job: Lote1
    timeoutInMinutes: 60
    steps:
    - script: ant dev-deploy -f ${{ variables.appName }}/modules/ant/build.xml -Dpath=ic
    - script: ant unit-tests-batch1 -Dpath=ic -f ${{ variables.appName }}/modules/ant/continuous-build.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'build/reports/unitarias/raw/batch1/*.xml'
        testRunTitle: 'Reporte Lote 1'
  - job: Lote2
    timeoutInMinutes: 60
    steps:
    - script: ant dev-deploy -f ${{ variables.appName }}/modules/ant/build.xml -Dpath=ic
    - script: ant unit-tests-batch2 -Dpath=ic -f ${{ variables.appName }}/modules/ant/continuous-build.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'build/reports/unitarias/raw/batch2/*.xml'
        testRunTitle: 'Reporte Lote 2'
  - job: Lote3
    timeoutInMinutes: 60
    steps:
    - script: ant dev-deploy -f ${{ variables.appName }}/modules/ant/build.xml -Dpath=ic
    - script: ant unit-tests-batch3 -Dpath=ic -f ${{ variables.appName }}/modules/ant/continuous-build.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'build/reports/unitarias/raw/batch3/*.xml'
        testRunTitle: 'Reporte Lote 3'
  - job: Lote4
    timeoutInMinutes: 60
    steps:
    - script: ant dev-deploy -f ${{ variables.appName }}/modules/ant/build.xml -Dpath=ic
    - script: ant unit-tests-batch4 -Dpath=ic -f ${{ variables.appName }}/modules/ant/continuous-build.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'build/reports/unitarias/raw/batch4/*.xml'
        testRunTitle: 'Reporte Lote 4'
  - job: Lote5
    timeoutInMinutes: 60
    steps:
    - script: ant dev-deploy -f ${{ variables.appName }}/modules/ant/build.xml -Dpath=ic
    - script: ant unit-tests-batch5 -Dpath=ic -f ${{ variables.appName }}/modules/ant/continuous-build.xml
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'build/reports/unitarias/raw/batch5/*.xml'
        testRunTitle: 'Reporte Lote 5'